version: '3.7'

services:
    gcc_10:
        build:
            context: ../
            dockerfile: docker/gcc/Dockerfile
            target: GCC_10
        volumes:
            - ../:/project
        command: make -j8
