name: Build Dev Images

on:
    workflow_dispatch:

jobs:
    gcc_10:
        name: Ubuntu Focal / GCC 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Build Image
              run: docker build -t ghcr.io/peymanmortazavi/garlic-model:gcc-10 --target GCC_10 --file docker/Dockerfile .

            - name: Push Image
              run: docker push ghcr.io/peymanmortazavi/garlic-model:gcc-10
