name: Garlic Model PR Tests

on:
    pull_request:

jobs:
    gcc_10:
        name: Compile with GCC 10 and C++ 20
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Build and Run Tests
              run: docker run --rm ghcr.io/peymanmortazavi/garlic-model:gcc-10 bash -c "make -j8 && make test"
