name: Update Documentations

on:
    workflow_dispatch:

jobs:
    update_docs:
        name: Update GH Pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Doxygen
              run: sudo apt install doxygen graphviz -y

            - name: Generate Docs
              run: doxygen docs/Doxyfile
