name: Update Documentations

on:
    workflow_dispatch:

jobs:
    update_docs:
        name: Update GH Pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Doxygen
              run: sudo apt install doxygen graphviz -y

            - name: Generate Docs
              run: doxygen docs/Doxyfile
            
             - name: Deploy 🚀
               uses: JamesIves/github-pages-deploy-action@4.1.0
               with:
                   branch: gh-pages # The branch the action should deploy to.
                   folder: docs/output/html # The folder the action should deploy.
